### ISSUE TITLE
Add noscript tag for users who have javascript disabled

### ISSUE THREAD

**Issue by juergenweb** [dominiquevienne/honeypot#3]
Hello dominique,

here is another idea to prevent users with javascript disabled of filling out the honeypot field. I am not sure if bots can read this noscript tag and will be warned not to fill out the field or not.
It would be just a small addition to change the input mask of the honeypotfield by adding a configurable noscript tag.

`private $_honeypotInputNoscriptText = 'Please leave this field empty';
if(!empty($config['honeypotInputNoscriptText'])) {
        $this->setHoneypotInputNoscriptText($config['honeypotInputNoscriptText']);
}
private $_honeypotInputMask           = '<noscript>[$honeypotInputNoscriptText]</noscript><input class="[$honeypotInputClass]" type="[$honeypotInputType]" name="[$honeypotInputName]" autocomplete="off" value="" />';`

So its just an idea

**Comment by dominiquevienne** [comment]
Hi @juergenweb , 

I clearly understand what you expect from this feature. Unfortunately, I am quite sure it will decrease a lot the efficiency of the honeypot. 
Indeed, bots will read the HTML source and will see the <noscript> content. Because some may understand specific sentences (moreover in English), they will tag this field as honeypot by detecting "not fill" or "field empty" catch phrase. 

It's also important to understand that users with
- JS disabled are now not legit internet users. JS is now mandatory on every site
- CSS disabled are also specific users

The only thing that comes in mind to me is, to stay WCAG2 compliant, this form field could create problems. Indeed, I do not know if visual impaired readers does implement Javascript by default. 

For this reason and also in order to give the best experience to everyone, this feature could be integrated as optionnal, disabled by default.

**Comment by juergenweb** [comment]
So I was also not sure if bots can understand the noscript tag. So it was just an idea. Leaving the code as it is will be ok. No need for modification.

Thanks for your efforts
