### ISSUE TITLE
Counter of attempts increases if page is reloaded without pressing submit button

### ISSUE THREAD

**Issue by juergenweb** [dominiquevienne/honeypot#5]
Hi, 
I have my honeypot validation code inside the `if ( isset( $_POST['Submit'] ) ) { }` statement but if I press the page reload button of the browser the failed attempts will be increased. 
I think the attempt counter should not be increased if the submit button will not be clicked.

I have discovered this behavior by loading the form via Ajax in a modal first. Everytime the modal was loaded the counter increases by 1.

Maybe if you have time to take a look at this issue.

Just to clearify: A user (or a bot) will not be blocked if the reload button of the browser is clicked more than the max failure attempts, but the counter increases. In this case no values are entered in the form. Every page reload force a counter increament, but the counter increament should only take place if the submit button was clicked. A page reload should not be counted as a failed attempt. As I pointed out above it will especially leads to problems if the form is loaded via Ajax. Every Ajax page load will be counted as an failed attempt. 

Thank you

**Comment by dominiquevienne** [comment]
Hi @juergenweb , 

Could you please upload your code (Form and action scripts) here so I can check how the honeypot validation is instancied?

Thanks

**Comment by juergenweb** [comment]
hi dominique,

here is my code:

```
<?php
namespace ProcessWire;
//create honeypot form object
$configarrayform = array(
    'honeypotInputClass' => 'myCssClass'
);
$oForm           = new \Dominiquevienne\Honeypot\Form($configarrayform);
if (isset($_POST['maincontactform_button'])) {
        //start honeypot validation
        $configarray = array(
            'minFormCompletionTime' => 10
        );
        $oHoneypot   = new \Dominiquevienne\Honeypot\Honeypot($configarray);
        $checks      = $oHoneypot->checks(true);
        $af          = array_filter($checks);
        if ($af == $checks) {
          //no honeypot validation erros
        } else {
          //there were honeypot validation errors detected - do something
        }                
   } 
}
//start time check
$oForm->timeCheck();
$honeypotInputs = '<div class="uk-form-row" style="margin-top:0"><div class="uk-form-controls">' . $oForm->inputs() . '</div></div>';
// Here comes the HTML of the form with the honeypot field
```

This is the short version of my code because the complete form code includes several markup and validation functions - so it will be to much because I would have to upload a lot of files and classes.

In short:

- I start with creating a new honeypot form object at the beginning of the page
```
//create honeypot form object
$configarrayform = array(
    'honeypotInputClass' => 'myCssClass'
);
$oForm           = new \Dominiquevienne\Honeypot\Form($configarrayform);
```

- Inside the POST brackets I  start with creating a new honepot object for the checks
```
//start honeypot validation
        $configarray = array(
            'minFormCompletionTime' => 10
        );
        $oHoneypot   = new \Dominiquevienne\Honeypot\Honeypot($configarray);
        $checks      = $oHoneypot->checks(true);
        $af          = array_filter($checks);
        if ($af == $checks) {
          //no honeypot validation erros
        } else {
          //there were honeypot validation errors detected - do something
        } 
```

- After the closing POST brackets I have included the time check and created the markup for the honeypot field.
```
$oForm->timeCheck();
$honeypotInputs = '<div class="uk-form-row" style="margin-top:0"><div class="uk-form-controls">' . $oForm->inputs() . '</div></div>';
```

This is the way I have included the code.

```
$_SESSION['honeypotAttempts']
```

This is the session variable which will be increased after each page reload.

Maybe this will help you

**Comment by dominiquevienne** [comment]
After some researches, I face with a question:
- does this refresh come before submitting the form once or after?

The simpleForm.php example will not increase the counter before submitting the form once... but will increase the same counter if the page is reloaded after a submission. This is a normal behaviour in order to prevent from form flooding. 

Let's imagine a form which would send emails... and a bot... The bot will try to reload the form after a successful submission... and if infinite reload is possible, mail server could be under heavy load. 

P.S.> please, use https://help.github.com/articles/creating-and-highlighting-code-blocks/ for your code blocks so code formatting is respected. ;)

**Comment by juergenweb** [comment]
Thanks for the hint of "highlighting code blocks" - I didnt know this.

The counter will be increased before the submit button was clicked for the first time. So loading the page only and hitting the reload button several times leads to an increament in my case.

Fe if I load the form via Ajax and I press the submit button for the first time I get a failed attempt number of 2. First failed attempt is loading the page via Ajax and the second is caused by pressing the submit button.

This is the strange behavior. My first thought was that it was initalized somewhere else on every page load (like my init.php). But I couldnt find a code line of the honypot class on pages which will be loaded on every page load. So they are only on the template file of the rendered page.

If it works for you without increament before submission the error must be on my side.

**Comment by dominiquevienne** [comment]
This is also a normal behaviour...

When loading the form for the first time, here is a var_dump() of what could look like the $_SESSION var
```
array(5) {
   ["honeypotTimeCheckStart"]=>
   int(1503923347)
   ["honeypotMethod"]=>
   string(4) "POST"
   ["honeypotAttempts"]=>
   int(1)
   ["honeypotInputName"]=>
   string(12) "hiddenfield1"
   ["honeypotToken"]=>
   string(24) "n9tXIRxdtV6nvRtr79uKFfOR"
   }
```

This dump is done before any submission. The counter is increased on every render of the form. As you can see, honeypotAttempts is already set to 1

**Why?**
This is done like that because some bots could render the form several times before trying to submit data in order to machine learn it. 

I understand it could be a rock in your shoe but, in fact, a refresh is no more standard in users behaviour. You can also work around by 
- resetting the $_SESSION values depending on your specific project
- increase authorized attempts by config values

Let me know

**Comment by juergenweb** [comment]
Ok, I see. I will try to integrate a Ajax request condition and if the page ist loaded via Ajax I will reduce the attempt session variable with -1. Otherwise I always get 2, 4, 6,... attempts (attempts will be doubled - requesting the page and loading the form).
I will post my results here after successfull adaption.

Thanks
